//--------------------------------------------------------------------------------
// IDs for UI elements are defined here
//--------------------------------------------------------------------------------


#define ID_BTN_APP_OPEN           0xF000
#define ID_BTN_APP_DIR		        0xF001
#define ID_BTN_APP_SAVE           0xF002
#define ID_BTN_APP_UNDO           0xF003
#define ID_BTN_APP_REDO           0xF004
#define ID_BTN_APP_CUTOUT         0xF005
#define ID_BTN_APP_CUTIN          0xF006
#define ID_BTN_APP_ZOOMIN         0xF007
#define ID_BTN_APP_ZOOMOUT        0xF008
#define ID_BTN_APP_INFO           0xF009
#define ID_BTN_APP_QUIT           0xF00A

#define ID_BTN_WAVE_REC           0xF00B
#define ID_BTN_WAVE_PAUSE         0xF00C
#define ID_BTN_WAVE_PLAY          0xF00D
#define ID_BTN_WAVE_STOP          0xF00E
#define ID_BTN_WAVE_MARKIN        0xF00F
#define ID_BTN_WAVE_MARKOUT       0xF010
#define ID_BTN_WAVE_PLAYFROM      0xF017
#define ID_BTN_WAVE_PLAYTILL      0xF018
#define ID_BTN_WAVE_PLAYIN        0xF019
#define ID_BTN_WAVE_PLAYOUT       0xF01A
#define ID_BTN_WAVE_YOUK          0xF01B
				  
#define ID_ITEM_LOAD_SELECTED     0xF01C
#define ID_BTN_LOAD_OK            0xF01D
#define ID_BTN_LOAD_CANCEL        0xF01E
				  
#define ID_BTN_REC_PLAY           0xF01F
#define ID_BTN_REC_REC            0xF020
#define ID_BTN_REC_PAUSE          0xF021
#define ID_BTN_REC_EDIT           0xF024

#define ID_ITEM_DIR_SELECTED      0xF025
#define ID_BTN_DIR_OK             0xF026
#define ID_BTN_DIR_CANCEL         0xF027

#define ID_ITEM_REC_RATE_SEL      0xF028
#define ID_ITEM_REC_BITS_SEL      0xF029
#define ID_ITEM_REC_CHAN_SEL      0xF02A

#define ID_ITEM_SAVEDIR_SELECTED  0xF02B
#define ID_BTN_SAVEDIR_OK         0xF02C
#define ID_BTN_SAVEDIR_CANCEL     0xF02D
