//--------------------------------------------------------------------------------
// Commands for communication protocol with PPT remote control.
#define CMD_RUNPPT              'R'
#define CMD_RETURN              'r'
#define CMD_OPEN                'O'
#define CMD_PREVIEW             'I'
#define CMD_NEXT                '+' 
#define CMD_PREV                '-'
#define CMD_FIRST               'F' 
#define CMD_LAST                'L'
#define CMD_GOTO                'G'
#define CMD_BLACK               'B'
#define CMD_WHITE               'W'
#define CMD_STOP                'X'
#define CMD_CLOSE               'Q'
#define CMD_CLEAR               'C'
#define CMD_HIDDEN              'S'
#define CMD_TIMENEW             'T'
#define CMD_TIMEOLD             't'
#define CMD_MOUSE               'M'
#define CMD_ARROW               'A'
#define CMD_PEN                 'P'   
#define CMD_HIDE                'H'
#define CMD_HIDEDELAY           'h'
#define CMD_CMENU               'm'  
#define CMD_NEXTHL              'n' 
#define CMD_PREVHL              'p'
#define CMD_CLICKHL             'K'
#define CMD_OVERHL              'V'
#define CMD_FILEINFO            'f'

#define ACK_RUN                 '1'
#define ACK_COUNT               '2'
#define ACK_PREV                '3'
#define ACK_NFO                 '4'
#define ACK_HL                  '5'
#define ACK_QUIT                '6'
#define ACK_FILEINFO            '7'
                                
#define ERR                     '#'